Social2023/urls.py
"""Social2023 URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'image'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></
    script>
    <script>
        const csrftoken = Cookies.get('csrftoken');
        document.addEventListener('DOMContentLoaded', (event) => {
        // DOM loaded
        {% block domready %}
        {% endblock %}
    })
    </script>
</head>
<body>
<div id="header">
    <span class="logo">Заклыдки</span>
    {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %} class="selected"{% endif %}>
                <a href="{% url "dashboard" %}">Панель управления</a>
            </li>
            <li {% if section == "image" %}class="selected"{% endif %}>
                <a href="{% url "images:list" %}">Изображения</a>
            </li>

            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="{% url "user_list" %}">Пользователи</a>
            </li>

        </ul>
    {% endif %}
    <span class="user">
        {% if request.user.is_authenticated %}
            Приветствую Вас {{ request.user.first_name|default:request.user.username }},
            <a href="{% url "logout" %}">Выйти</a>
        {% else %}
            <a href="{% url "login" %}">Войти</a>
        {% endif %}
</span>
</div>
{#Уведомления#}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>